
language: generic

branches:
  only:
    - which-rustc-fails

matrix:
  include:
    - os: linux
      env: SPEC=nightly-2017-05-25
    - os: linux
      env: SPEC=nightly-2017-06-01
    - os: linux
      env: SPEC=nightly-2017-06-08
    - os: linux
      env: SPEC=nightly-2017-06-15

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain $SPEC -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - export PATH="$HOME/.cargo/bin:$PATH" && rustc -V
  - cargo -V

script:
  - cargo build --no-default-features
  - cargo test --no-default-features

dist: trusty
sudo: required
