
language: generic

branches:
  only:
    - which-rustc-fails

matrix:
  include:
    - os: linux
      env: SPEC=nightly-2017-03-19
    - os: linux
      env: SPEC=nightly-2017-04-19
    - os: linux
      env: SPEC=nightly-2017-05-19
    - os: linux
      env: SPEC=nightly-2017-06-19
    - os: linux
      env: SPEC=nightly-2017-07-19

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain $SPEC -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - export PATH="$HOME/.cargo/bin:$PATH" && rustc -V
  - cargo -V

script:
  - cargo build --no-default-features
  - cargo test --no-default-features

dist: trusty
sudo: required
